# Generated by Django 6.0.3 on 2026-06-12 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='username',
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='deposit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank',
            name='withdraw_count',
            field=models.IntegerField(default=0),
        ),
    ]
